/**
 * List of Brazilian banks as:
 * {
 *   "001": "Banco do Brasil S.A.",
 *   "341": "Banco Itaú S.A.",
 *   "033": "Banco Santander (Brasil) S.A.",
 *    ...
 * }
 */
export const banks = new Map()
  .set("001", "Banco do Brasil S.A.")
  .set("341", "Banco Itaú S.A.")
  .set("033", "Banco Santander (Brasil) S.A.")
  .set("356", "Banco Real S.A. (antigo)")
  .set("652", "Itaú Unibanco Holding S.A.")
  .set("237", "Banco Bradesco S.A.")
  .set("745", "Banco Citibank S.A.")
  .set("399", "HSBC Bank Brasil S.A. – Banco Múltiplo")
  .set("104", "Caixa Econômica Federal")
  .set("389", "Banco Mercantil do Brasil S.A.")
  .set("453", "Banco Rural S.A.")
  .set("422", "Banco Safra S.A.")
  .set("633", "Banco Rendimento S.A.")
  .set("246", "Banco ABC Brasil S.A.")
  .set("025", "Banco Alfa S.A.")
  .set("641", "Banco Alvorada S.A.")
  .set("029", "Banco Banerj S.A.")
  .set("038", "Banco Banestado S.A.")
  .set("000", "Banco Bankpar S.A.")
  .set("740", "Banco Barclays S.A.")
  .set("107", "Banco BBM S.A.")
  .set("031", "Banco Beg S.A.")
  .set("096", "Banco BM&F de Serviços de Liquidação e Custódia S.A")
  .set("318", "Banco BMG S.A.")
  .set("752", "Banco BNP Paribas Brasil S.A.")
  .set("248", "Banco Boavista Interatlântico S.A.")
  .set("036", "Banco Bradesco BBI S.A.")
  .set("204", "Banco Bradesco Cartões S.A.")
  .set("225", "Banco Brascan S.A.")
  .set("044", "Banco BVA S.A.")
  .set("263", "Banco Cacique S.A.")
  .set("473", "Banco Caixa Geral – Brasil S.A.")
  .set("222", "Banco Calyon Brasil S.A.")
  .set("040", "Banco Cargill S.A.")
  .set("M08", "Banco Citicard S.A.")
  .set("M19", "Banco CNH Capital S.A.")
  .set("215", "Banco Comercial e de Investimento Sudameris S.A.")
  .set("756", "Banco Cooperativo do Brasil S.A. – BANCOOB")
  .set("748", "Banco Cooperativo Sicredi S.A.")
  .set("505", "Banco Credit Suisse (Brasil) S.A.")
  .set("229", "Banco Cruzeiro do Sul S.A.")
  .set("003", "Banco da Amazônia S.A.")
  .set("083-3", "Banco da China Brasil S.A.")
  .set("707", "Banco Daycoval S.A.")
  .set("M06", "Banco de Lage Landen Brasil S.A.")
  .set("024", "Banco de Pernambuco S.A. – BANDEPE")
  .set("456", "Banco de Tokyo-Mitsubishi UFJ Brasil S.A.")
  .set("214", "Banco Dibens S.A.")
  .set("047", "Banco do Estado de Sergipe S.A.")
  .set("037", "Banco do Estado do Pará S.A.")
  .set("041", "Banco do Estado do Rio Grande do Sul S.A.")
  .set("004", "Banco do Nordeste do Brasil S.A.")
  .set("265", "Banco Fator S.A.")
  .set("M03", "Banco Fiat S.A.")
  .set("224", "Banco Fibra S.A.")
  .set("626", "Banco Ficsa S.A.")
  .set("394", "Banco Finasa BMC S.A.")
  .set("M18", "Banco Ford S.A.")
  .set("233", "Banco GE Capital S.A.")
  .set("734", "Banco Gerdau S.A.")
  .set("M07", "Banco GMAC S.A.")
  .set("612", "Banco Guanabara S.A.")
  .set("M22", "Banco Honda S.A.")
  .set("063", "Banco Ibi S.A. Banco Múltiplo")
  .set("M11", "Banco IBM S.A.")
  .set("604", "Banco Industrial do Brasil S.A.")
  .set("320", "Banco Industrial e Comercial S.A.")
  .set("653", "Banco Indusval S.A.")
  .set("630", "Banco Intercap S.A.")
  .set("249", "Banco Investcred Unibanco S.A.")
  .set("184", "Banco Itaú BBA S.A.")
  .set("479", "Banco ItaúBank S.A")
  .set("M09", "Banco Itaucred Financiamentos S.A.")
  .set("376", "Banco J. P. Morgan S.A.")
  .set("074", "Banco J. Safra S.A.")
  .set("217", "Banco John Deere S.A.")
  .set("065", "Banco Lemon S.A.")
  .set("600", "Banco Luso Brasileiro S.A.")
  .set("755", "Banco Merrill Lynch de Investimentos S.A.")
  .set("746", "Banco Modal S.A.")
  .set("151", "Banco Nossa Caixa S.A.")
  .set("045", "Banco Opportunity S.A.")
  .set("623", "Banco Panamericano S.A.")
  .set("611", "Banco Paulista S.A.")
  .set("643", "Banco Pine S.A.")
  .set("638", "Banco Prosper S.A.")
  .set("747", "Banco Rabobank International Brasil S.A.")
  .set("M16", "Banco Rodobens S.A.")
  .set("072", "Banco Rural Mais S.A.")
  .set("250", "Banco Schahin S.A.")
  .set("749", "Banco Simples S.A.")
  .set("366", "Banco Société Générale Brasil S.A.")
  .set("637", "Banco Sofisa S.A.")
  .set("464", "Banco Sumitomo Mitsui Brasileiro S.A.")
  .set("082-5", "Banco Topázio S.A.")
  .set("M20", "Banco Toyota do Brasil S.A.")
  .set("634", "Banco Triângulo S.A.")
  .set("208", "Banco UBS Pactual S.A.")
  .set("M14", "Banco Volkswagen S.A.")
  .set("655", "Banco Votorantim S.A.")
  .set("610", "Banco VR S.A.")
  .set("370", "Banco WestLB do Brasil S.A.")
  .set("021", "BANESTES S.A. Banco do Estado do Espírito Santo")
  .set("719", "Banif-Banco Internacional do Funchal (Brasil)S.A.")
  .set("073", "BB Banco Popular do Brasil S.A.")
  .set("078", "BES Investimento do Brasil S.A.-Banco de Investimento")
  .set("069", "BPN Brasil Banco Múltiplo S.A.")
  .set("070", "BRB – Banco de Brasília S.A.")
  .set("477", "Citibank N.A.")
  .set("081-7", "Concórdia Banco S.A.")
  .set("487", "Deutsche Bank S.A. – Banco Alemão")
  .set("751", "Dresdner Bank Brasil S.A. – Banco Múltiplo")
  .set("062", "Hipercard Banco Múltiplo S.A.")
  .set("492", "ING Bank N.V.")
  .set("488", "JPMorgan Chase Bank")
  .set("409", "UNIBANCO – União de Bancos Brasileiros S.A.")
  .set("230", "Unicard Banco Múltiplo S.A.")
