/**
 * List of Brazilian banks as:
 * {
 *   "001": "Banco do Brasil S.A.",
 *   "341": "Banco Itaú S.A.",
 *   "033": "Banco Santander (Brasil) S.A.",
 *    ...
 * }
 */
export const banks = new Map()
  .set("246", "Banco ABC Brasil S.A.")
  .set("748", "Banco Cooperativo Sicredi S.A.")
  .set("117", "Advanced Cc Ltda")
  .set("121", "Banco Agibank S.A.")
  .set("172", "Albatross Ccv S.A")
  .set("188", "Ativa Investimentos S.A")
  .set("280", "Avista S.A. Crédito, Financiamento e Investimento")
  .set("080", "B&T Cc Ltda")
  .set("654", "Banco A.J.Renner S.A.")
  .set("075", "Banco ABN AMRO S.A")
  .set("025", "Banco Alfa S.A.")
  .set("641", "Banco Alvorada S.A.")
  .set("065", "Banco Andbank (Brasil) S.A.")
  .set("213", "Banco Arbi S.A.")
  .set("096", "Banco B3 S.A.")
  .set("024", "Banco BANDEPE S.A.")
  .set("318", "Banco BMG S.A.")
  .set("752", "Banco BNP Paribas Brasil S.A.")
  .set("107", "Banco BOCOM BBM S.A.")
  .set("063", "Banco Bradescard S.A.")
  .set("036", "Banco Bradesco BBI S.A.")
  .set("122", "Banco Bradesco BERJ S.A.")
  .set("204", "Banco Bradesco Cartões S.A.")
  .set("394", "Banco Bradesco Financiamentos S.A.")
  .set("237", "Banco Bradesco S.A.")
  .set("218", "Banco BS2 S.A.")
  .set("208", "Banco BTG Pactual S.A.")
  .set("336", "Banco C6 S.A – C6 Bank")
  .set("473", "Banco Caixa Geral – Brasil S.A.")
  .set("412", "Banco Capital S.A.")
  .set("040", "Banco Cargill S.A.")
  .set("368", "Banco Carrefour")
  .set("266", "Banco Cédula S.A.")
  .set("739", "Banco Cetelem S.A.")
  .set("233", "Banco Cifra S.A.")
  .set("745", "Banco Citibank S.A.")
  .set("241", "Banco Clássico S.A.")
  .set("756", "Banco Cooperativo do Brasil S.A. – BANCOOB")
  .set("222", "Banco Credit Agricole Brasil S.A.")
  .set("505", "Banco Credit Suisse (Brasil) S.A.")
  .set("069", "Banco Crefisa S.A.")
  .set("003", "Banco da Amazônia S.A.")
  .set("083", "Banco da China Brasil S.A.")
  .set("707", "Banco Daycoval S.A.")
  .set("051", "Banco de Desenvolvimento do Espírito Santo S.A.")
  .set("300", "Banco de La Nacion Argentina")
  .set("495", "Banco de La Provincia de Buenos Aires")
  .set("494", "Banco de La Republica Oriental del Uruguay")
  .set("335", "Banco Digio S.A")
  .set("001", "Banco do Brasil S.A.")
  .set("047", "Banco do Estado de Sergipe S.A.")
  .set("037", "Banco do Estado do Pará S.A.")
  .set("041", "Banco do Estado do Rio Grande do Sul S.A.")
  .set("004", "Banco do Nordeste do Brasil S.A.")
  .set("196", "Banco Fair Corretora de Câmbio S.A")
  .set("265", "Banco Fator S.A.")
  .set("224", "Banco Fibra S.A.")
  .set("626", "Banco Ficsa S.A.")
  .set("094", "Banco Finaxis S.A.")
  .set("612", "Banco Guanabara S.A.")
  .set("012", "Banco Inbursa S.A.")
  .set("604", "Banco Industrial do Brasil S.A.")
  .set("653", "Banco Indusval S.A.")
  .set("077", "Banco Inter S.A.")
  .set("249", "Banco Investcred Unibanco S.A.")
  .set("184", "Banco Itaú BBA S.A.")
  .set("029", "Banco Itaú Consignado S.A.")
  .set("479", "Banco ItauBank S.A")
  .set("376", "Banco J. P. Morgan S.A.")
  .set("074", "Banco J. Safra S.A.")
  .set("217", "Banco John Deere S.A.")
  .set("076", "Banco KDB S.A.")
  .set("757", "Banco KEB HANA do Brasil S.A.")
  .set("600", "Banco Luso Brasileiro S.A.")
  .set("243", "Banco Máxima S.A.")
  .set("720", "Banco Maxinvest S.A.")
  .set("389", "Banco Mercantil do Brasil S.A.")
  .set("370", "Banco Mizuho do Brasil S.A.")
  .set("746", "Banco Modal S.A.")
  .set("066", "Banco Morgan Stanley S.A.")
  .set("456", "Banco MUFG Brasil S.A.")
  .set("007", "Banco Nacional de Desenvolvimento Econômico e Social – BNDES")
  .set("169", "Banco Olé Bonsucesso Consignado S.A.")
  .set("111", "Banco Oliveira Trust Dtvm S.A")
  .set("079", "Banco Original do Agronegócio S.A.")
  .set("212", "Banco Original S.A.")
  .set("712", "Banco Ourinvest S.A.")
  .set("623", "Banco PAN S.A.")
  .set("611", "Banco Paulista S.A.")
  .set("643", "Banco Pine S.A.")
  .set("658", "Banco Porto Real de Investimentos S.A.")
  .set("747", "Banco Rabobank International Brasil S.A.")
  .set("633", "Banco Rendimento S.A.")
  .set("741", "Banco Ribeirão Preto S.A.")
  .set("120", "Banco Rodobens S.A.")
  .set("422", "Banco Safra S.A.")
  .set("033", "Banco Santander (Brasil) S.A.")
  .set("743", "Banco Semear S.A.")
  .set("754", "Banco Sistema S.A.")
  .set("630", "Banco Smartbank S.A.")
  .set("366", "Banco Société Générale Brasil S.A.")
  .set("637", "Banco Sofisa S.A.")
  .set("464", "Banco Sumitomo Mitsui Brasileiro S.A.")
  .set("082", "Banco Topázio S.A.")
  .set("634", "Banco Triângulo S.A.")
  .set("018", "Banco Tricury S.A.")
  .set("655", "Banco Votorantim S.A.")
  .set("610", "Banco VR S.A.")
  .set("119", "Banco Western Union do Brasil S.A.")
  .set("124", "Banco Woori Bank do Brasil S.A.")
  .set("348", "Banco Xp S/A")
  .set("081", "BancoSeguro S.A.")
  .set("021", "BANESTES S.A. Banco do Estado do Espírito Santo")
  .set("755", "Bank of America Merrill Lynch Banco Múltiplo S.A.")
  .set("268", "Barigui Companhia Hipotecária")
  .set("250", "BCV – Banco de Crédito e Varejo S.A.")
  .set("144", "BEXS Banco de Câmbio S.A.")
  .set("253", "Bexs Corretora de Câmbio S/A")
  .set("134", "Bgc Liquidez Dtvm Ltda")
  .set("017", "BNY Mellon Banco S.A.")
  .set("301", "Bpp Instituição De Pagamentos S.A")
  .set("126", "BR Partners Banco de Investimento S.A.")
  .set("070", "BRB – Banco de Brasília S.A.")
  .set("092", "Brickell S.A. Crédito, Financiamento e Investimento")
  .set("173", "BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.")
  .set("142", "Broker Brasil Cc Ltda")
  .set("292", "BS2 Distribuidora de Títulos e Valores Mobiliários S.A.")
  .set("011", "C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)")
  .set("104", "Caixa Econômica Federal")
  .set("288", "Carol Distribuidora de Títulos e Valor Mobiliários Ltda")
  .set("130", "Caruana Scfi")
  .set("159", "Casa Credito S.A")
  .set("016", "Ccm Desp Trâns Sc E Rs")
  .set("089", "Ccr Reg Mogiana")
  .set("114", "Central Cooperativa De Crédito No Estado Do Espírito Santo")
  .set("114-", "Central das Cooperativas de Economia e Crédito Mútuo doEstado do Espírito Santo Ltda.")
  .set("320", "China Construction Bank (Brasil) Banco Múltiplo S.A.")
  .set("477", "Citibank N.A.")
  .set("180", "Cm Capital Markets Cctvm Ltda")
  .set("127", "Codepe Cvc S.A")
  .set("163", "Commerzbank Brasil S.A. – Banco Múltiplo")
  .set("060", "Confidence Cc S.A")
  .set("085", "Coop Central Ailos")
  .set("097", "Cooperativa Central de Crédito Noroeste Brasileiro Ltda.")
  .set("085-", "Cooperativa Central de Crédito Urbano-CECRED")
  .set("090-", "Cooperativa Central de Economia e Crédito Mutuo – SICOOB UNIMAIS")
  .set("087-", "Cooperativa Central de Economia e Crédito Mútuo das Unicredsde Santa Catarina e Paraná")
  .set("089-", "Cooperativa de Crédito Rural da Região da Mogiana")
  .set("286", "Cooperativa de Crédito Rural De Ouro")
  .set("279", "Cooperativa de Crédito Rural de Primavera Do Leste")
  .set("273", "Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel")
  .set("098", "Credialiança Ccr")
  .set("098-", "CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL")
  .set("010", "Credicoamo")
  .set("133", "Cresol Confederação")
  .set("182", "Dacasa Financeira S/A")
  .set("487", "Deutsche Bank S.A. – Banco Alemão")
  .set("140", "Easynvest – Título Cv S.A")
  .set("149", "Facta S.A. Cfi")
  .set("285", "Frente Corretora de Câmbio Ltda.")
  .set("278", "Genial Investimentos Corretora de Valores Mobiliários S.A.")
  .set("138", "Get Money Cc Ltda")
  .set("064", "Goldman Sachs do Brasil Banco Múltiplo S.A.")
  .set("177", "Guide Investimentos S.A. Corretora de Valores")
  .set("146", "Guitta Corretora de Câmbio Ltda")
  .set("078", "Haitong Banco de Investimento do Brasil S.A.")
  .set("062", "Hipercard Banco Múltiplo S.A.")
  .set("189", "HS Financeira S/A Crédito, Financiamento e Investimentos")
  .set("269", "HSBC Brasil S.A. – Banco de Investimento")
  .set("271", "IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.")
  .set("157", "Icap Do Brasil Ctvm Ltda")
  .set("132", "ICBC do Brasil Banco Múltiplo S.A.")
  .set("492", "ING Bank N.V.")
  .set("139", "Intesa Sanpaolo Brasil S.A. – Banco Múltiplo")
  .set("652", "Itaú Unibanco Holding S.A.")
  .set("341", "Itaú Unibanco S.A.")
  .set("488", "JPMorgan Chase Bank, National Association")
  .set("399", "Kirton Bank S.A. – Banco Múltiplo")
  .set("293", "Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.")
  .set("105", "Lecca Crédito, Financiamento e Investimento S/A")
  .set("145", "Levycam Ccv Ltda")
  .set("113", "Magliano S.A")
  .set("323", "Mercado Pago – Conta Do Mercado Livre")
  .set("128", "MS Bank S.A. Banco de Câmbio")
  .set("137", "Multimoney Cc Ltda")
  .set("014", "Natixis Brasil S.A. Banco Múltiplo")
  .set("191", "Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.")
  .set("753", "Novo Banco Continental S.A. – Banco Múltiplo")
  .set("260", "Nu Pagamentos S.A (Nubank)")
  .set("613", "Omni Banco S.A.")
  .set("290", "Pagseguro Internet S.A")
  .set("254", "Paraná Banco S.A.")
  .set("326", "Parati – Crédito Financiamento e Investimento S.A.")
  .set("194", "Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda")
  .set("174", "Pernambucanas Financ S.A")
  .set("100", "Planner Corretora De Valores S.A")
  .set("125", "Plural S.A. – Banco Múltiplo")
  .set("093", "Pólocred Scmepp Ltda")
  .set("108", "Portocred S.A")
  .set("283", "Rb Capital Investimentos Dtvm Ltda")
  .set("101", "Renascenca Dtvm Ltda")
  .set("270", "Sagitur Corretora de Câmbio Ltda.")
  .set("751", "Scotiabank Brasil S.A. Banco Múltiplo")
  .set("276", "Senff S.A. – Crédito, Financiamento e Investimento")
  .set("545", "Senso Ccvm S.A")
  .set("190", "Servicoop")
  .set("183", "Socred S.A")
  .set("299", "Sorocred Crédito, Financiamento e Investimento S.A.")
  .set("118", "Standard Chartered Bank (Brasil) S/A–Bco Invest.")
  .set("197", "Stone Pagamentos S.A")
  .set("340", "Super Pagamentos e Administração de Meios Eletrônicos S.A.")
  .set("095", "Travelex Banco de Câmbio S.A.")
  .set("143", "Treviso Corretora de Câmbio S.A.")
  .set("131", "Tullett Prebon Brasil Cvc Ltda")
  .set("129", "UBS Brasil Banco de Investimento S.A.")
  .set("091-", "Unicred Central do Rio Grande do Sul")
  .set("091", "Unicred Central Rs")
  .set("136", "Unicred Cooperativa")
  .set("099", "UNIPRIME Central – Central Interestadual de Cooperativas de Crédito Ltda.")
  .set("084", "Uniprime Norte do Paraná – Coop de Economia eCrédito Mútuo dos Médicos, Profissionais das Ciências")
  .set("298", "Vips Cc Ltda")
  .set("310", "Vortx Distribuidora de Títulos e Valores Mobiliários Ltda")
  .set("102", "Xp Investimentos S.A")
